#!/bin/bash
#
# Check tot test the speed of a drive and trigger a faster storage
# in a vmware setting with HDD/SDD configurations
#
# Door Arie van den Heuvel
# Datum 18-09-2023
#
# Uitvoeren van de test en afronden naar een heel getal
#
speed=$(hdparm -t /dev/sda | grep disk | awk '{ print $11 }')
#
# Rapportage als local check naar check_mk
#
echo "<<<local>>>"
echo "P Drive_Speed Count=$speed;2000"
