#!/bin/bash
#
# Test om de snelhed van een drive te testen en bij te houden
#
# Door Arie van den Heuvel
# Datum 18-09-2023
#
# Uitvoren van de test en afronden naar een heel getal
#
speed=$(hdparm -t /dev/sda | grep disk | awk '{ print $11 }'| numfmt --from=iec --to=iec --format=%0f)
#
# Rapportage als local check naar check_mk
#
echo "<<<local>>>"
echo "P Drive_Speed Count=$speed;2000"
