#!/bin/bash
#
# Description: This script monitors the memory usage of a specified process
# using pmap and reports the number of mapped and deleted memory sections.
# It's designed to help detect potential memory leaks.
#
# By: Arie van den Heuvel
# First setup: 14-11-2025
# Improvements: 22-11-2025
#
# Getting the procesid of the aplication
pid=$(pidof /opt/vtmis/ARAMIS/bin/x86_64-linux-gnu/aramis)
#
# Collecting the total number of mapped items
total=$(pmap -x $pid | wc -l)
#
# Collectin the total of deleted items
deleted=$(pmap -x $pid | grep deleted | wc -l)
#
# Reporting the items to check_mk
echo "<<<local>>>"
echo "P pmap_deleted Count=$deleted;500"
echo "P pmap_total Count=$total;5000"
