#!/bin/bash
#
# local check to monitor deleted sections in a memorymap by pmap
# to see if there is a memoryleak going on with a application
#
# Arie van den Heuve
# 14-11-2025
#
# Collecting the total number of mapped items
#
total=$(mypid=$(pidof /opt/vtmis/ARAMIS/bin/x86_64-linux-gnu/aramis) ; pmap -x $mypid | wc -l)
# Collectin the total of deleted items
#
deleted=$(mypid=$(pidof /opt/vtmis/ARAMIS/bin/x86_64-linux-gnu/aramis) ; pmap -x $mypid | grep deleted | wc -l)
#
# Reporting the items to check_mk
echo "<<<local>>>"
echo "P pmap_deleted Count=$deleted;500"
echo "P pmap_total Count=$total;5000"
